// Admin form field definitions (moved here from the old /api/admin/crud route).
// `table` is the Supabase table each admin tab edits.

export const MODEL_CONFIG: Record<string, { table: string; fields: { name: string; label: string; type: 'text' | 'number' | 'boolean' | 'textarea' | 'select' | 'image'; options?: string[] }[] }> = {
  catShops: {
    table: 'CatShop',
    fields: [
      { name: 'shopName', label: 'দোকানের নাম', type: 'text' },
      { name: 'ownerName', label: 'মালিকের নাম', type: 'text' },
      { name: 'shopImage', label: 'দোকানের ছবি', type: 'image' },
      { name: 'catImage', label: 'বিড়ালের ছবি', type: 'image' },
      { name: 'address', label: 'ঠিকানা', type: 'text' },
      { name: 'division', label: 'বিভাগ', type: 'select', options: ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh'] },
      { name: 'district', label: 'জেলা', type: 'text' },
      { name: 'area', label: 'এলাকা', type: 'text' },
      { name: 'phone', label: 'ফোন', type: 'text' },
      { name: 'whatsapp', label: 'WhatsApp', type: 'text' },
      { name: 'facebook', label: 'Facebook', type: 'text' },
      { name: 'website', label: 'Website', type: 'text' },
      { name: 'mapUrl', label: 'Map URL', type: 'text' },
      { name: 'openingHours', label: 'খোলার সময়', type: 'text' },
      { name: 'availableBreeds', label: 'উপলব্ধ জাত', type: 'text' },
      { name: 'description', label: 'বর্ণনা', type: 'textarea' },
      { name: 'verified', label: 'যাচাই', type: 'select', options: ['Not Verified', 'Pending', 'Verified'] },
    ],
  },
  catFoodShops: {
    table: 'CatFoodShop',
    fields: [
      { name: 'shopName', label: 'দোকানের নাম', type: 'text' },
      { name: 'ownerName', label: 'মালিকের নাম', type: 'text' },
      { name: 'shopImage', label: 'দোকানের ছবি', type: 'image' },
      { name: 'address', label: 'ঠিকানা', type: 'text' },
      { name: 'division', label: 'বিভাগ', type: 'select', options: ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh'] },
      { name: 'district', label: 'জেলা', type: 'text' },
      { name: 'area', label: 'এলাকা', type: 'text' },
      { name: 'phone', label: 'ফোন', type: 'text' },
      { name: 'whatsapp', label: 'WhatsApp', type: 'text' },
      { name: 'facebook', label: 'Facebook', type: 'text' },
      { name: 'mapUrl', label: 'Map URL', type: 'text' },
      { name: 'openingHours', label: 'খোলার সময়', type: 'text' },
      { name: 'homeDelivery', label: 'হোম ডেলিভারি', type: 'boolean' },
      { name: 'availableBrands', label: 'উপলব্ধ ব্র্যান্ড', type: 'text' },
      { name: 'foodTypes', label: 'খাবারের ধরন', type: 'text' },
      { name: 'priceInfo', label: 'দামের তথ্য', type: 'text' },
      { name: 'description', label: 'বর্ণনা', type: 'textarea' },
      { name: 'verified', label: 'যাচাই', type: 'select', options: ['Not Verified', 'Pending', 'Verified'] },
    ],
  },
  vetClinics: {
    table: 'VeterinaryClinic',
    fields: [
      { name: 'clinicName', label: 'ক্লিনিকের নাম', type: 'text' },
      { name: 'doctorName', label: 'ডাক্তারের নাম', type: 'text' },
      { name: 'specialization', label: 'বিশেষায়ন', type: 'text' },
      { name: 'clinicImage', label: 'ক্লিনিকের ছবি', type: 'image' },
      { name: 'address', label: 'ঠিকানা', type: 'text' },
      { name: 'division', label: 'বিভাগ', type: 'select', options: ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh'] },
      { name: 'district', label: 'জেলা', type: 'text' },
      { name: 'area', label: 'এলাকা', type: 'text' },
      { name: 'phone', label: 'ফোন', type: 'text' },
      { name: 'emergencyPhone', label: 'ইমারজেন্সি ফোন', type: 'text' },
      { name: 'whatsapp', label: 'WhatsApp', type: 'text' },
      { name: 'openingHours', label: 'খোলার সময়', type: 'text' },
      { name: 'emergencyService', label: 'ইমারজেন্সি সেবা', type: 'boolean' },
      { name: 'mapUrl', label: 'Map URL', type: 'text' },
      { name: 'website', label: 'Website', type: 'text' },
      { name: 'services', label: 'সেবাসমূহ', type: 'text' },
      { name: 'description', label: 'বর্ণনা', type: 'textarea' },
      { name: 'verified', label: 'যাচাই', type: 'select', options: ['Not Verified', 'Pending', 'Verified'] },
    ],
  },
  serviceProviders: {
    table: 'ServiceProvider',
    fields: [
      { name: 'providerName', label: 'প্রদানকারীর নাম', type: 'text' },
      { name: 'businessName', label: 'ব্যবসার নাম', type: 'text' },
      { name: 'type', label: 'ধরন', type: 'select', options: ['Grooming', 'Boarding', 'Training', 'Sitting', 'Photography', 'Transport', 'Pharmacy', 'Rescue'] },
      { name: 'image', label: 'ছবি', type: 'image' },
      { name: 'address', label: 'ঠিকানা', type: 'text' },
      { name: 'division', label: 'বিভাগ', type: 'select', options: ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh'] },
      { name: 'district', label: 'জেলা', type: 'text' },
      { name: 'area', label: 'এলাকা', type: 'text' },
      { name: 'phone', label: 'ফোন', type: 'text' },
      { name: 'whatsapp', label: 'WhatsApp', type: 'text' },
      { name: 'facebook', label: 'Facebook', type: 'text' },
      { name: 'mapUrl', label: 'Map URL', type: 'text' },
      { name: 'openingHours', label: 'খোলার সময়', type: 'text' },
      { name: 'homeService', label: 'হোম সার্ভিস', type: 'boolean' },
      { name: 'description', label: 'বর্ণনা', type: 'textarea' },
      { name: 'verified', label: 'যাচাই', type: 'select', options: ['Not Verified', 'Pending', 'Verified'] },
    ],
  },
  breeds: {
    table: 'Breed',
    fields: [
      { name: 'name', label: 'নাম', type: 'text' },
      { name: 'bnName', label: 'বাংলা নাম', type: 'text' },
      { name: 'origin', label: 'উৎপত্তি', type: 'text' },
      { name: 'temperament', label: 'স্বভাব', type: 'text' },
      { name: 'lifespan', label: 'আয়ুষ্কাল', type: 'text' },
      { name: 'weight', label: 'ওজন', type: 'text' },
      { name: 'price', label: 'দাম', type: 'text' },
      { name: 'rarity', label: 'বিরলতা', type: 'select', options: ['Common', 'Premium', 'Exotic'] },
      { name: 'category', label: 'বিভাগ', type: 'select', options: ['Pedigree', 'Local', 'Exotic'] },
      { name: 'description', label: 'বর্ণনা', type: 'textarea' },
      { name: 'careLevel', label: 'যত্নের স্তর', type: 'select', options: ['Easy', 'Moderate', 'High'] },
      { name: 'goodWithKids', label: 'বাচ্চাদের সাথে ভালো', type: 'boolean' },
      { name: 'hypoallergenic', label: 'হাইপোঅ্যালার্জেনিক', type: 'boolean' },
      { name: 'image', label: 'ছবি', type: 'image' },
    ],
  },
  articles: {
    table: 'Article',
    fields: [
      { name: 'title', label: 'শিরোনাম', type: 'text' },
      { name: 'category', label: 'বিভাগ', type: 'select', options: ['Nutrition', 'Health', 'Behavior', 'Grooming', 'Kitten', 'Senior'] },
      { name: 'image', label: 'ছবি', type: 'image' },
      { name: 'excerpt', label: 'সারসংক্ষেপ', type: 'textarea' },
      { name: 'content', label: 'বিষয়বস্তু', type: 'textarea' },
      { name: 'author', label: 'লেখক', type: 'text' },
      { name: 'readTime', label: 'পড়ার সময় (মিনিট)', type: 'number' },
      { name: 'tags', label: 'ট্যাগ', type: 'text' },
      { name: 'featured', label: 'ফিচার্ড', type: 'boolean' },
    ],
  },
  events: {
    table: 'Event',
    fields: [
      { name: 'title', label: 'শিরোনাম', type: 'text' },
      { name: 'type', label: 'ধরন', type: 'select', options: ['Cat Show', 'Meetup', 'Workshop', 'Adoption Drive', 'Webinar'] },
      { name: 'image', label: 'ছবি', type: 'image' },
      { name: 'date', label: 'তারিখ', type: 'text' },
      { name: 'time', label: 'সময়', type: 'text' },
      { name: 'venue', label: 'ভেন্যু', type: 'text' },
      { name: 'city', label: 'শহর', type: 'text' },
      { name: 'description', label: 'বর্ণনা', type: 'textarea' },
      { name: 'capacity', label: 'ধারণক্ষমতা', type: 'number' },
    ],
  },
  community: {
    table: 'CommunityPost',
    fields: [
      { name: 'author', label: 'লেখক', type: 'text' },
      { name: 'title', label: 'শিরোনাম', type: 'text' },
      { name: 'image', label: 'ছবি', type: 'image' },
      { name: 'body', label: 'বিষয়বস্তু', type: 'textarea' },
      { name: 'category', label: 'ধরন', type: 'select', options: ['Discussion', 'Question', 'Story', 'Photo', 'Advice'] },
      { name: 'city', label: 'শহর', type: 'text' },
    ],
  },
  lostfound: {
    table: 'LostFound',
    fields: [
      { name: 'type', label: 'ধরন', type: 'select', options: ['Lost', 'Found'] },
      { name: 'catName', label: 'বিড়ালের নাম', type: 'text' },
      { name: 'image', label: 'বিড়ালের ছবি', type: 'image' },
      { name: 'breed', label: 'জাত', type: 'text' },
      { name: 'color', label: 'রঙ', type: 'text' },
      { name: 'location', label: 'অবস্থান', type: 'text' },
      { name: 'city', label: 'শহর', type: 'text' },
      { name: 'date', label: 'তারিখ', type: 'text' },
      { name: 'contact', label: 'যোগাযোগ', type: 'text' },
      { name: 'phone', label: 'ফোন', type: 'text' },
      { name: 'description', label: 'বর্ণনা', type: 'textarea' },
      { name: 'status', label: 'অবস্থা', type: 'select', options: ['Active', 'Reunited'] },
    ],
  },
  gallery: {
    table: 'Gallery',
    fields: [
      { name: 'title', label: 'শিরোনাম', type: 'text' },
      { name: 'cat', label: 'বিড়ালের নাম', type: 'text' },
      { name: 'owner', label: 'মালিক', type: 'text' },
      { name: 'city', label: 'শহর', type: 'text' },
      { name: 'image', label: 'ছবি', type: 'image' },
      { name: 'caption', label: 'ক্যাপশন', type: 'text' },
    ],
  },
  testimonials: {
    table: 'Testimonial',
    fields: [
      { name: 'name', label: 'নাম', type: 'text' },
      { name: 'avatar', label: 'প্রোফাইল ছবি', type: 'image' },
      { name: 'role', label: 'ভূমিকা', type: 'text' },
      { name: 'city', label: 'শহর', type: 'text' },
      { name: 'rating', label: 'রেটিং (১-৫)', type: 'number' },
      { name: 'quote', label: 'উক্তি', type: 'textarea' },
      { name: 'catName', label: 'বিড়ালের নাম', type: 'text' },
      { name: 'featured', label: 'ফিচার্ড', type: 'boolean' },
    ],
  },
  members: {
    table: 'Member',
    fields: [
      { name: 'name', label: 'নাম', type: 'text' },
      { name: 'avatar', label: 'প্রোফাইল ছবি', type: 'image' },
      { name: 'email', label: 'ইমেইল', type: 'text' },
      { name: 'phone', label: 'ফোন', type: 'text' },
      { name: 'city', label: 'শহর', type: 'text' },
      { name: 'plan', label: 'প্ল্যান', type: 'select', options: ['Free', 'Silver', 'Gold'] },
      { name: 'cats', label: 'বিড়ালের সংখ্যা', type: 'number' },
    ],
  },
  contacts: {
    table: 'Contact',
    fields: [
      { name: 'name', label: 'নাম', type: 'text' },
      { name: 'email', label: 'ইমেইল', type: 'text' },
      { name: 'subject', label: 'বিষয়', type: 'text' },
      { name: 'message', label: 'বার্তা', type: 'textarea' },
    ],
  },
  newsletter: {
    table: 'Newsletter',
    fields: [
      { name: 'email', label: 'ইমেইল', type: 'text' },
    ],
  },
}
